#!/usr/bin/python

import os
import sys
import time
import shutil
import argparse
import subprocess

from fedulas.formulas import Formulas,FormulasError

debug = True

def main():

    cp = argparse.ArgumentParser(
            description=u"manage and apply Formulas",
            add_help=False
        )

    cp.add_argument("-c", "--config", help="Path to configuration file",
        default='/etc/formulas/formulas.conf:~/.formulas/formulas.conf')

    (args, other) = cp.parse_known_args()

#    print "args: {0}".format(args)
#    print "other: {0}".format(other)
    f = Formulas(args.config)

    p = argparse.ArgumentParser(
        # Inherit options from config_parser
        parents=[cp],
        # print script description with -h/--help
        description=__doc__,
        # Don't mess with format of description
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    sp = p.add_subparsers()

    p_apply = sp.add_parser("apply", help=u"apply a Formula")
    p_apply.add_argument("-p", "--path", help="Override default path to formulas")
    p_apply.add_argument("-o", "--hosts", default=['localhost'], nargs='+', help="Host(s) to apply formula. Default: localhost")
    p_apply.add_argument("name", help=u"Formula name")
    p_apply.set_defaults(func=f.apply_formula)

    args = p.parse_args()

    if debug:
        try:
            args.func(args)
        except Exception as e:
            print e
            sys.exit(1)
    else:
        try:
            args.func(args)
        except Exception as e:
            print e
            sys.exit(1)

if __name__ == "__main__":
    raise SystemExit(main())
