#!/usr/bin/python

import os
import sys
import time
import shutil
import argparse
import subprocess

from fedulas.formulas import Formulas,FormulasError

debug = True

def main():

    f = Formulas()

    p = argparse.ArgumentParser(
            description=u"manage and apply Formulas",
        )

    sp = p.add_subparsers()

    p_deplist = sp.add_parser("apply", help=u"apply a Formula")
    p_deplist.add_argument("name", help=u"Formula name")
    p_deplist.set_defaults(func=f.apply_formula)


    args = p.parse_args()

    if debug:
        try:
            args.func(args)
        except Exception as e:
            print e.value
            sys.exit(1)
    else:
        try:
            args.func(args)
        except Exception as e:
            print e
            sys.exit(1)

if __name__ == "__main__":
    raise SystemExit(main())
